#!/usr/bin/env escript
main(_) ->
    code:add_path("ebin/"),
    code:add_path("deps/emysql/"),
    code:add_path("deps/emysql/ebin/"),
    io:format("~p",[lists:last(code:get_path())]),
    {ok, Conf} = file:consult("reltool.config"),
    {ok, Spec} = reltool:get_target_spec(Conf),
    reltool:eval_target_spec(Spec, code:root_dir(), "rel")
        .
